
services:
  # frontend:
  #   image: ntkitn/taskflow-frontend:latest
  #   ports:
  #     - "80:80"
  backend:
    image: ntkitn/taskflow-backend
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/TaskFlow?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
    deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 5
    networks:
      - TaskFlowNetwork

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaskFlow
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - TaskFlowNetwork
  # redis:
  #   image: redis:latest

volumes:
  mysql-data:

networks:
  TaskFlowNetwork: 
    name: TaskFlowNetwork
    driver: bridge
